project:
  type: website
  output-dir: docs

website:
  title: "TechTonic Bytes with Jiwan"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/jiwan-gharti
      - icon: linkedin
        href: https://www.linkedin.com/in/jiwan-gharti/
      - icon: gear-fill
        href: https://linktr.ee/jiwangharti
  site-url: "https://jiwan-gharti.github.io/blogs"
  repo-url: "https://github.com/jiwan-gharti/blogs"
format:
  html:
    theme:
      - lux
    css: styles.css



